name: NodeJS with Webpack

on:
  push:
    branches: [ master ]
 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build
      run: |
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        yarn install
        yarn build
        cd dist
        git config --global user.name 'Bot'
        git config --global user.email 'dylanmashini@users.noreply.github.com'
        git init
        git add -A
        git commit -m 'deploy'
        git push -f master:gh-pages

        
